- hosts: all
  vars:
    execstart: 'capp_system_info_server.service'
    server_host: '0.0.0.0'
    server_port: '9999'
    secret: 'secret'
  tasks:
    - name: install service systemd unit file
      template: src=service.j2 dest=/etc/systemd/system/capp_system_info_server.service
    - name: reload systemd unit configuration
      command: systemctl daemon-reload
    - name: start capp_system_info_server
      systemd: state=started name=capp_system_info_server daemon_reload=yes