# playbook - создание systemd сервиса, и копирование исполняемого файла
- hosts: all
  vars:
    execstart: '/usr/local/bin/capp_system_info_server'
    server_host: '0.0.0.0'
    server_port: '9999'
    secret: 'secret'
  tasks:
    - name: Check my user name
      local_action: command whoami
      become: yes
      become_user: root
    - name: Copy capp_system_info_server
      ansible.builtin.copy:
        src: ./capp_system_info_server
        dest: /usr/local/bin/capp_system_info_server
      become: yes
      become_user: root
    - name: install service systemd unit file
      template: src=service.j2 dest=/etc/systemd/system/capp_system_info_server.service
      become: yes
      become_user: root
    - name: reload systemd unit configuration
      command: systemctl daemon-reload
      become: yes
      become_user: root
    - name: start capp_system_info_server
      systemd: state=started name=capp_system_info_server daemon_reload=yes
      become: yes
      become_user: root